### ISSUE TITLE
Can't build with Typescript 5.x.x

### ISSUE THREAD

**Issue by ahettlin** [Ionaru/easy-markdown-editor#562]
**Describe the bug**
When building with typescript 5.x.x, multiple of the following error are produced:

```
node_modules/@types/codemirror/index.d.ts:553:39 - error TS2304: Cannot find name 'DocumentAndElementEventHandlersEventMap'.

       on<K extends DOMEvent & keyof DocumentAndElementEventHandlersEventMap>(
```

**Expected behavior**
Should build successfully. It works with typescript 4.9.5.

**Version information**
- OS: Windows 11
- Browser: N/A
- EasyMDE version: 2.18.0

**Additional context**
I'm guessing this could be an upstream issue with codemirror, but as I'm not familiar with either project, I at least wanted to file this here.  I assume `DocumentAndElementEventHandlersEventMap` was removed in typescript 5?

**Comment by ahettlin** [comment]
Overriding `@types/codemirror` from`easymde` with `"@types/codemirror": "5.60.10"` works for typescript 5.1.6

**Comment by Ionaru** [comment]
Thank you for reporting this issue and investigating a fix.
It sounds like upgrading the `typescript` and `@types/codemirror` packages fixes the issue, I'll do that soon.

**Comment by Ionaru** [comment]
Both typescript 4 and 5 should be able to build correctly :)

**Comment by ahettlin** [comment]
That was fast! Thanks!
